#if !canImport(ObjectiveC)
  import XCTest

  extension hey_sapTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__hey_sapTests = [
      ("testExample", testExample)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(hey_sapTests.__allTests__hey_sapTests)
    ]
  }
#endif
