#if !canImport(ObjectiveC)
  import XCTest

  extension HeySapTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HeySapTests = [
      ("testExample", testExample)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    [
      testCase(HeySapTests.__allTests__HeySapTests)
    ]
  }
#endif
